### ISSUE TITLE
properly clean up nic when instance type is unavailable

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#154]
A deployment failed because an instance type was unavailable in the region, and a subsequent attempt with a corrected manifest failed because the NICs associated with the deleted VMs stuck around. Manually removing the NICs resolved the issue.

Also review code around the NIC clean up to make sure there are no other cases like the one above.

**Comment by bingosummer** [comment]
In v11, the nic is not cleaned up because of the `invalid disk name` error.
Does the issue of cleaning up nic also happen in v12?

**Comment by AbelHu** [comment]
@cppforlife When an instance type is not available in the region, an exception will be thrown in create_vm. The exception should be caught and cleanup code will delete the nic. But because of #151 in v11 another exception will be thrown so that the nic is not deleted. 
After #115 was fixed, this will not be an issue.

**Comment by AbelHu** [comment]
@cppforlife Close it since it has been fixed in v12.
