### ISSUE TITLE
Can the CPI create storage account containers automatically?

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry-incubator/bosh-azure-cpi-release#195]
We often find that customers attempt to use empty storage accounts with no `bosh` and `stemcell` containers.  Could the CPI create those container if they are missing?  Ideally with `private` access so they can be used in premium and standard storage accounts.
@sadvani

**Comment by AbelHu** [comment]
@dsboulder Older version last year will check and create those containers. @cppforlife suggested us to remove it for better performance because the containers are created only once.
The access of the container stemcell under the default storage account must be set to 'Public read access for blobs only' because CPI needs to copy stemcells to other storage accounts.

**Comment by bingosummer** [comment]
I would add the following points:
1. For the default storage account, CPI won't create those containers just as @AbelHu said.
2. For the additional storage account (which can be specified in resource_pool), if the storage account doesn't exist, CPI will create the storage account and containers. If the storage account already exists, CPI won't check and create those containers.

**Comment by dsboulder** [comment]
If it's possible to create those containers for the "additional" storage accounts, that would be awesome.
