### ISSUE TITLE
ad app create command failed

### ISSUE THREAD

**Issue by kamoljan** [cloudfoundry-incubator/bosh-azure-cpi-release#272]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version:  
BOSH     Version: 1.3262.26.0
CF       Version: 6.26.0+9c9a261fd.2017-04-06
Diego    Version:

### Stemcell
Version:
Distro:
  - [ ] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureStack
  - [ ] Others:
- Location: Japan East
- Subscription ID: ?
- Resource Group Name: 

### Issue Details
Getting `Request_ResourceNotFound` error message during `./create-service-principal.sh`
### Logs (*Please redact all sensitive information in your logs*)
```
❯❯❯ ./create-service-principal.sh                                                                                                                                                               ⏎
Check if Azure CLI has been installed...
Set Azure CLI to arm mode...
info:    Executing command config mode
info:    New mode is arm
info:    config mode command OK
...
info:    account set command OK
Please input identifier for your Service Principal with (1) MINIMUM length of 8, (2) NO space [press Enter to use default identifier BOSHv201705282934]: KamolBoshLah
Use KamolBoshLah as identifier...
Create Active Directory application...
error:   {"odata.error":{"code":"Request_ResourceNotFound","message":{"lang":"en","value":"Resource not found for the segment 'me'."}}}
error:   Error information has been recorded to /Users/kamol/.azure/azure.err
error:   ad app create command failed
```

**Comment by bingosummer** [comment]
Thanks @kamoljan for reporting this issue. I just tried `./create-service-principal.sh`, and it seems working.
1. Could you please re-run `./create-service-principal.sh` to confirm this issue is a consistent issue? In the issue https://github.com/Azure/acs-engine/issues/97, re-issuing the command makes it complete successfully.
2. If the issue is consistent, please collect the Azure CLI version and the error information in `/Users/kamol/.azure/azure.err`. I suggest you to open an issue in [azure-cli](https://github.com/Azure/azure-xplat-cli/issues) since it's possibly an azure-cli issue. Or, if you can provide the steps to reproduce, I am happy to submit an issue for you. Does it make sense?

**Comment by bingosummer** [comment]
@kamoljan 
Do you have any progress? Please let us know if you hit any issues.

**Comment by kamoljan** [comment]
@bingosummer it works, thank you!
