### ISSUE TITLE
Unable to create a VM  in an availability set  because the requested size is not available in the current hardware cluster

### ISSUE THREAD

**Issue by OlegGerber** [cloudfoundry-incubator/bosh-azure-cpi-release#367]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 32
BOSH     Version: "264.4.0"

### Stemcell
Version:
Distro:
  - [x] Ubuntu
### Environment
- Azure Environment:
  - [x] Azure

### Issue Details
VM upgrade/downgrade to the different VM series sometime fails.
I know that root of the issue is Availability Set feature, however bosh cpi can easily check the hardware availability in the specific cluster before the upgrade procedure and recreate the "problematic" availability set during the upgrade, so the new availability set will be assigned to the right hardware cluster,

### Logs (*Please redact all sensitive information in your logs*)

Error message: {
  "error": {
    "code": "InvalidParameter",
    "target": "instance_type",
    "message": "Unable to create the VM  in availability set 'bosh-azure-hotfix-application-logging-sleeve-forwarder' because the requested size Standard_A2_v2 is not available in the current hardware cluster. The available sizes are: ....
  }

### Repro steps (*if necessary, delete otherwise*)
change VM size in the manifest and run deployment

**Comment by bingosummer** [comment]
Thanks for reporting the issue, @OlegGerber . I agree that the root cause is the availability set feature. 

Here is how BOSH director communicate with CPI:
When upgrading/resizing VMs, BOSH director will ask CPI to delete the VM and recreate it one by one. It means that when deleting/creating one VM, CPI doesn't know that whether the director is going to delete/create other VMs. 

If the availability set name is changed, CPI can create VMs with the requested size in a new availability set, and the new VMs and availability sets are in a different cluster. But there is a requiremnt: the VMs should **NOT** be in a load balancer. Otherwise, you will hit #368 .

If the availability set name is not changed, CPI can NOT create VMs with the requested size if the size is not available in the current hardware cluster. The reason is:
1. CPI can NOT create a new availability set with the same name.
2. The availability set can't be deleted if there are VMs in it.
3. Deleting VMs are in parallel.
Because of the above reasons, CPI doesn't have an easy way to recreate the "problematic" availability set during the upgrade.

I agree that CPI can easily check whether the size is available in the specific cluster when creating a VM. But before deleting the VM, CPI doesn't know what the target new VM size. If **BOSH director can pass more information about the target new VM size when it calls delete_vm**, CPI can check whether the new VM size is available and report an early error. Then the old VMs won't be deleted. I think, it's a valid feature for BOSH director. For other CPIs, I believe, the **feature** is also useful.

CC: @cppforlife

**Comment by bingosummer** [comment]
@OlegGerber Could you please share the region of the VM and the old VM size? I'd like to reproduce the issue and look for a workaround.

**Comment by OlegGerber** [comment]
@bingosummer Thank you for the assistance.
The region is: West Europe
The sizes are: Standard_A2_v2 <-> Standard_D2s_v3
p.s:
As you understand the issue not always reproduced, it is depend on the hardware availability in the specific cluster....

**Comment by bingosummer** [comment]
Standard SKU LB doesn't have the limitation in #368. So, if you are using standard LB, you can change the availability set name to recreate the availability set.

**Comment by tanjoht** [comment]
@bingosummer how can we change the name of the availability set? we are running into the scenario where we want to upgrade the vms to a new instance_type that isn't supported. We don't have any load balancers or anything
