### ISSUE TITLE
arm template is not functional for ubuntu 16.04 

### ISSUE THREAD

**Issue by jkujovic** [cloudfoundry-incubator/bosh-azure-cpi-release#395]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version:
BOSH     Version:
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details
ARM problem install ubuntu  16.04 on azure . error on deploy azure-cli  problem gpg 

### Logs (*Please redact all sensitive information in your logs*)

W: GPG error: https://packages.microsoft.com/repos/azure-cli wheezy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
W: The repository 'https://packages.microsoft.com/repos/azure-cli xenial InRelease' is not signed.
W: There is no public key available for the following key IDs:
EB3E94ADBE1229CF  

The command "apt-get install -qq azure-cli" failed and exited 

### Repro steps (*if necessary, delete otherwise*)
1.
2.
3.
4.
5.

**Comment by bingosummer** [comment]
Thanks @jkujovic for reporting the issue.
This is because the key is deprecated. Please run `curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -` and then try to install azure cli again.
If it can fix your issue, you can try to deploy the template `https://github.com/bingosummer/azure-quickstart-templates/blob/bump-version/bosh-setup/azuredeploy.json` and use `https://raw.githubusercontent.com/bingosummer/azure-quickstart-templates/bump-version/bosh-setup/` as the parameter `_artifactsLocation`.
The fix will be merged to upstream soon.

**Comment by bingosummer** [comment]
FYI: https://github.com/Azure/azure-quickstart-templates/pull/4685

**Comment by jkujovic** [comment]
@bingosummer 
Than you, very much . Your  suggestion working for me. Thank again.

Jan
