### ISSUE TITLE
Azure template issues

### ISSUE THREAD

**Issue by haydonryan** [cloudfoundry-incubator/bosh-azure-cpi-release#58]
(Note https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-setup sent me here for feedback).

The Jumpbox 30gb "/" drive size is too small -  Downloading a few copies of elastic runtime distributions and services fills the drive. 100gb would be betterer.

a /24 network is too small - a large deployment of Cloud Foundry will easily fill this, needs to be a /22.  

It'd also be nice to have installed by default:
cf cli
uaac 
mysqlclient and pgclient / pgdump
ag-silversearcher

**Comment by AbelHu** [comment]
Thanks for your feedback. You can edit the template after clicking the deploy button to change the VM size and the network CIDR. 
We will update the default value for the network CIDR later.
For those packages, we leave them to you because the versions change so fast or you may want to choose a different version.

**Comment by haydonryan** [comment]
Great Thanks Abel.

**Comment by bingosummer** [comment]
@Abel and @haydonryan 
With this [PR](https://github.com/Azure/azure-quickstart-templates/pull/1226), the template will create a /20 subnet by default.
And users can customize the variable `subnetAddressRangeForCloudFoundry`.
I think, we can close this issue.
